version: "3"
services:
  web:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3001:80"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=seleniumdb
